In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[2]

2

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

**broadcast**

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

**something to be careful about**

In [13]:
my_arr = np.arange(0,11)

In [14]:
slice_of_my_arr = my_arr[0:6]

In [15]:
slice_of_my_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
slice_of_my_arr[:] = 99

In [17]:
slice_of_my_arr

array([99, 99, 99, 99, 99, 99])

**changed the value of the original array**

In [18]:
my_arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

**need to use the .copy() method to avoid the broadcast**

In [19]:
my_arr2 = my_arr.copy

In [21]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [22]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
arr_2d[0]

array([ 5, 10, 15])

In [24]:
arr_2d[2][1]

40

In [25]:
arr_2d[1,2]

30

In [26]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [27]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [28]:
arr1 = np.arange(1,11)

In [34]:
bool_arr = arr1 > 5

In [35]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [36]:
arr1[bool_arr]

array([ 6,  7,  8,  9, 10])

In [32]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
arr1[arr1<3]

array([1, 2])

In [39]:
practice = np.arange(50).reshape(5,10)

In [40]:
practice

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [41]:
practice[1:5,1:10]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [31, 32, 33, 34, 35, 36, 37, 38, 39],
       [41, 42, 43, 44, 45, 46, 47, 48, 49]])