## NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

**can transform lists into arrays**

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**similar to python's range function**

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**only even numbers**

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

**only zeros**

In [10]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [13]:
np.zeros((3,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

**spaced ranges**

In [14]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

**identity matrix**

In [16]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

**randoms**

In [17]:
np.random.rand(5)

array([ 0.73206404,  0.31069839,  0.67239667,  0.35916698,  0.86855299])

In [18]:
np.random.rand(5,5)

array([[ 0.47888281,  0.54901943,  0.6688053 ,  0.07045968,  0.1779674 ],
       [ 0.82780509,  0.7897945 ,  0.75137965,  0.60073039,  0.37349213],
       [ 0.35976506,  0.70015712,  0.30352564,  0.444636  ,  0.2032644 ],
       [ 0.75006149,  0.45888719,  0.7446954 ,  0.61128467,  0.06918704],
       [ 0.95015392,  0.92585243,  0.97512212,  0.21199876,  0.47322779]])

**get two randoms from the standard normal distribution**

In [19]:
np.random.randn(2)

array([ 0.50109755, -0.18384404])

In [20]:
np.random.randint(1,100,3)

array([35, 18, 17])

**Let's see some array functions**

In [21]:
arr = np.arange(25)

In [22]:
ranarr = np.random.randint(0,50,10)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr

array([20,  9, 12, 23, 15, 44, 38, 41, 25, 12])

In [25]:
ranarr.max()

44

In [27]:
ranarr.argmax()

5

In [28]:
ranarr.argmin()

1

In [29]:
arr.shape

(25,)

In [31]:
arr = arr.reshape(5,5)

In [32]:
arr.shape

(5, 5)

In [33]:
arr.dtype

dtype('int64')